### ISSUE TITLE
개발 기술 스택 픽스

### ISSUE THREAD

**Issue by subak94** [comgongju/comgongju#11]

**Comment by soyoung-k** [comment]
# WEB
- 테스트 주도 개발 TDD(Test-Driven Development)
  - [React Testing Library](https://testing-library.com/docs/react-testing-library/intro)이용
- Typescript + React + Rx
- Next.js 이용하여 SSR(Server-side-rendering)

**Comment by Soojung-Shin** [comment]
# iOS
* 순수 swift or RxSwift or Combine (고민..)
* Networking library : AlamoFire
* Layout : snapKit layout or flex layout or swiftUI
---
### 고민되는 점
1) RxSwift를 제대로 안써봤다는 점... 공부한지 오래돼서 익숙치않다.
  MVVM 구조 잘 짤 수 있을까?
2) Combine & swiftUI 제일 써보고 싶은데 iOS13 이후 지원이라 지원기기 환경이 너무 좁아진다.
3) snapKit 레이아웃은 오토레이아웃 기반이라 퍼포먼스 떨어지지 않을지 걱정 (퍼포먼스가 중요한 앱은 아닐 것 같긴 하지만)

**Comment by jae-ran** [comment]
# Server
* Spring-boot 
* AWS EC2(Ubuntu) 구축
* Restful API 개발, Swagger를 이용해 문서 자동화
* Mybatis, JPA 동시 적용
* TDD 적용

### 고민
1) JPA에 대한 개념이 아직 제대로 잡혀있지 않다.. 공부해서 개념을 제대로 숙지하고 적용해보기!
2)  TDD도 마찬가지, 직접 환경을 적용해보고 TDD방식에 조금씩 적응해보기! 
할 수 있겠지..?

**Comment by subak94** [comment]
@jae-ran TDD 대단하군,,,,,,b
